# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
    - repo: github.com/PyCQA/flake8
        rev: ''
        hooks:
        - id: flake8

    - repo: github.com/psf/black
        rev: ''
        hooks:
        - id: black
