version: "3.8"

services:

  server:
    container_name: Fastapi-server

    depends_on:
      - db

    restart: always

    build:
      context: . # compose file에 대한 상대적인 위치
      dockerfile: Dockerfile

    ports:
      - 80:80

    environment:
      TZ: "Asia/Seoul"

    networks:
      - aid

  db:
    image: mongo:latest

    restart: always

    container_name: db

    ports:
      - 27017:27017

    expose:
      - 27017

    env_file:
      - ./app/env/.db.env

    networks:
      - aid

networks:
  aid:
    driver: bridge

volumes:
  data-vol:
    driver: local
