version: "3.8"

services:
  db:
    image: mongo:latest

    restart: always

    container_name: db

    ports:
      - 27017:27017

    expose:
      - 27017

    environment:
      MONGO_INITDB_ROOT_USERNAME: super_user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: test
