[tool.pytest.ini_options]
pythonpath = [
    "./app/backend",
    "./app",
    "."
]

env = [
    "mongo_user=admin_user",
    "mongo_password=password",
    "mongo_host=localhost",
    "mongo_port=27017"
]
